accounts/urls.py
from django.urls import path
from django.contrib import admin
#from django.contrib.auth.views import LoginView, LogoutView 
from . import views
#from .views import RegistarView, IndexView, LoginView, LogoutView

app_name = "accounts"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('registar/', views.RegistarView.as_view(), name="registar"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    # path('home/', views.HomeView.as_view(), name="home"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('create_shift/', views.Create_shiftView.as_view(), name="create_shift"),
    path('shift/', views.ShiftView.as_view(), name="shift"),
    path('table/', views.TableView.as_view(), name="table"),
    path('board/', views.BoardView.as_view(), name="board"),
    path('create/', views.CreatePostView.as_view(), name="create"),
    path('shift_edit/', views.shift_edit, name='shift_edit'),
    path('shift_form/', views.shift_form, name='shift_form'),
    path('shift_delete/', views.shift_delete, name='shift_delete'),
    path('get_shifts/', views.get_shifts, name='get_shifts'),
    path('get_allshifts/', views.get_allshifts, name='get_allshifts'),
    path('get_allaccounts/', views.get_allaccounts, name='get_allaccounts'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'), #追加
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    # path('admin/', admin.site.urls),

]

app/urls.py
#from django.contrib import admin
#from django.urls import path

#urlpatterns = [
#    path('admin/', admin.site.urls),
#]

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")) # accounts.urls.pyを読み込むための設定を追加
]

templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <!-- <script src="../static/js/javascript.js"></script> -->
  
  <title>Account</title>
</head>

<body>

 
  {% include 'navbar.html' %}

  {% block content %}
  {% endblock content %}

</body>

</html>

templates/board.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}

<div class="title">掲示板</div>



<div class="container mt-3">
    {% for item in object_list %}
    <div class="allpost" role="alert">
        <p class="postname">{{item.user.last_name}}{{item.user.first_name}}</p>
        <div class="postcontent">
            <p class="posttitle">{{item.title}}</p>
            <p class="postmessage">{{item.message}}</p>
            <p class="posttime">{{item.created_at}}</p>
        </div>
    </div>
    {% endfor %}
</div>


<a href="{% url 'accounts:create' %}" ><span class="dli-plus-circle"><span></span></span></a>





{% endif %}
{% endblock content %}

templates/create_post.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="create_post">
   <p class="createtitle">新規作成</p>
 <form method="post">
   {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="sendbutton" value="Send!">
 </form>
</div>

 {% endif %}
{% endblock content %}

templates/create_shift.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
<!-- {% include 'navbar.html' %} -->

<div class="title">Submit Page -- {{user.last_name}}{{user.first_name}}</div>

<!-- <h3>Today is <span id="currentDate"></span></h3> -->
<div id="month">
    <button id="prevMonth">＜</button>
    <span id="currentYearMonth"></span>
    <button id="nextMonth">＞</button>
</div>
<br>

<div id="calendar"></div>

<div id="shiftModal" style="display:none;">
        <h3 id="modalDate"></h3>
        <button id="cancelShift">×</button>
        <label for="shiftInput"></label>
        <!-- <input type="text" id="shiftInput"> -->
        <br>
        <ul>
           <li>
                <input type="radio" id="lunchShift" name="shiftType" value="△">
                <label for="lunchShift" class="label">ランチ:△</label>
           </li>
           <li>
                <input type="radio" id="dinnerShift" name="shiftType" value="◯">
                <label for="dinnerShift" class="label">ディナー:◯</label>
            </li>
            <li>
                <input type="radio" id="11Shift" name="shiftType" value="△11">
                <label for="11Shift" class="label">11時～</label>
            </li>
            <li>
                <input type="radio" id="17Shift" name="shiftType" value="◯17">
                <label for="17Shift" class="label">17時～</label>
            </li>
            <li>
                <input type="radio" id="orShift" name="shiftType" value="☆">
                <label for="orShift" class="label">どっちでも:☆</label>
            </li>
            <li>
                <input type="radio" id="fullShift" name="shiftType" value="◎">
                <label for="fullShift" class="label">オーラス:◎</label>
            </li>
            <li>
                <input type="radio" id="NoShift" name="shiftType" value="✕">
                <label for="NoShift" class="label">休み:×</label>
            </li>
        </ul>
        
        <br>

        
        <button id="deleteShift">削除</button>
        <button id="saveShift">保存</button>

</div>



<script>

     function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    const csrfToken = getCookie('csrftoken');
    const shiftData = JSON.parse('{{ shift_data|escapejs }}');
    shifts = shiftData; 

</script>


<script src="../../static/js/calendar.js"></script>


{% endif %}
{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

    <div  id="loader">
        <div class="loader">
            <img src="../../static/image/unagi.png" alt="ウナギ" class="unagi">
        </div>
        <div class="loading">loading...</div>
    </div>
  
    <div class="content" id="content" style="display: none;">
        <div class="login-body">
            <div class="login-container">
                <button><a href="{% url 'accounts:login' %}" class="btn btn-primary">Login</a></button>
                <br>
            </div>
        </div>
    </div>



<script src="../../static/js/javascript.js"></script>
    
  
{% endblock content %}

templates/navbar.html
{% if user.is_authenticated %}
<div class="top">
    <div class="hamburger">
        <span></span>
        <span></span>
        <span></span>
    </div>
    <nav class="globalMenuSp">
        <ul>
            <li>
                <a class="item_profile" href="{% url 'accounts:profile' %}">設定</a>
            </li>
            <li>
                <a class="item_create_shift" href="{% url 'accounts:create_shift' %}">シフト提出</a>
            </li>
            <li>
                <a class="item_shift" href="{% url 'accounts:shift' %}">カレンダーシフト</a>
            </li>
            <li>
                <a class="item_shift" href="{% url 'accounts:table' %}">表シフト</a>
            </li>
            <li>
                <a class="item_shift" href="{% url 'accounts:board' %}">お知らせ</a>
            </li>
            <li>
                <form method="post" action="{% url 'accounts:logout' %}">
                    {% csrf_token %}
                        <button class="logout-button" type="submit">ログアウト</button>
                </form>
            </li>
        </ul>
    </nav>
</div>


<script src="../../static/js/navber.js"></script>

{% endif %}

templates/profile.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}

<div class="title">username  -- {{user.last_name}}{{user.first_name}}</div>
<div class="title">account_id -- {{user.account_id}} </div>

<div class="text-right">{{ form_name }}</div>
{% if form_name == "password_change" %}
{% else %}
    <button class="password_change"><a href="{% url 'accounts:password_change' %}" class="logout">パスワードの変更</a></button><br>
{% endif %}



{% if user.account_id|stringformat:"s"|first == "0" %}
<!-- account_idが0で始まるユーザーにのみ表示されるコンテンツ -->
    <div class="registar-button">
        <h3>ユーザー登録する</h3>
        <button>
            <a href="{% url 'accounts:registar' %}" class="btn btn-secondary">追加</a>
        </button>
    </div>


    <div class="userList">
        <h3>アカウント一覧</h3>
        <p>総アカウント数: {{ total_accounts }}</p>

        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>ユーザー名</th>
                    <th>最終ログイン</th>
                </tr>
            </thead>
            <tbody>
                {% for account in accounts %}
                <tr>
                    <td>{{account.account_id}}</td>
                    <td>{{ account.last_name }}{{account.first_name}}</td>
                    <td>{{ account.last_login|date:"Y/m/d H:i"|default:"未ログイン" }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">アカウントが登録されていません。</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        
        {% if is_paginated %}
        <nav aria-label="ページネーション">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">前へ</a></li>
                {% endif %}
                <li class="page-item active"><span class="page-link">{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span></li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">次へ</a></li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    

        <button>
            <a href="{% url 'admin:accounts_user_changelist' %}" class="admin">アカウント編集</a>
        </button>
    </div>


{% endif %}






<input type="file" id="file" />
<a href="javascript:void(0);" id="button">Select photo</a>
<a href="javascript:void(0);" id="delete-button">Delete photo</a> <!-- 追加: 削除ボタン -->
<div id="image-container"></div>


<script>

    var button = document.getElementById('button');
    var deleteButton = document.getElementById('delete-button');
    var imageContainer = document.getElementById('image-container');
    // clickされたら
    button.addEventListener('click', function () {
    // inputのclickメソッドを呼ぶ
        input.click();
    });

    function displayImage(url) {
            var img = new Image();
            img.src = url;
            // img.height = 400;
            img.width = 350;
            // var imageContainer = document.getElementById('image-container');
            imageContainer.innerHTML = ''; // 既存の画像を削除
            imageContainer.appendChild(img);
    }
     // ローカルストレージから画像を読み込んで表示
     var storedImage = localStorage.getItem('profileImage');
        if (storedImage) {
            displayImage(storedImage);
        }

        // 要素を取得
        var input = document.getElementById('file');
        // changeイベントでファイルの選択をキャッチ
        input.addEventListener('change', function (e) {
            var file = e.target.files[0];

            // FileReaderを初期化して、
            var fr = new FileReader();
            // ファイルが読み込み終わったあとの処理を書いておく
            fr.addEventListener('load', function() {
                var url = fr.result;
                // 画像を表示
                displayImage(url);
                // ローカルストレージに保存
                localStorage.setItem('profileImage', url);
            });
            // ファイルをデータURLとして読み込む
            fr.readAsDataURL(file);
        });

            // 削除ボタンがクリックされたら、画像を削除
        deleteButton.addEventListener('click', function () {
            localStorage.removeItem('profileImage'); // ローカルストレージから削除
            imageContainer.innerHTML = ''; // 表示されている画像を消す
            alert('写真を削除しました');
    });



</script>

{% endif %}
{% endblock content %}

templates/shift.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
<!-- {% include 'navbar.html' %} -->

<div class="title">Shift Page -- {{user.last_name}}{{user.first_name}}</div>

<!-- <h3>Today is <span id="currentDate"></span></h3> -->
<div id="month">
    <button id="prevMonth">＜</button>
    <span id="currentYearMonth"></span>
    <button id="nextMonth">＞</button>
</div>
<br>

<div id="calendar"></div>

<div id="shiftModal" style="display:none;">
        <h3 id="modalDate"></h3>
        <div id="shiftInfoContainer"></div>
        <button id="cancelShift">×</button>
</div>

<script src="../../static/js/shift.js"></script>


{% endif %}
{% endblock content %}

templates/table.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}

<div id="month">
    <button id="prevMonth">＜</button>
    <span id="currentYearMonth"></span>
    <button id="nextMonth">＞</button>
</div>
<br>

<div id="shiftTable"></div>

<div id="shiftTableModal" style="display:none;">
    <h3 id="TablemodalDate"></h3>
    <button id="cancelShift">×</button>
    <label for="shiftInput"></label>
    <!-- <input type="text" id="shiftInput"> -->
    <br>
    <ul>
       <li>
            <input type="radio" id="tlunchShift" name="shiftType" value="△">
            <label for="tlunchShift" class="label">ランチ:△</label>
       </li>
        <li>
            <input type="radio" id="t11Shift" name="shiftType" value="△11">
            <label for="t11Shift" class="label">11時～</label>
        </li>
       <li>
            <input type="radio" id="tdinnerShift" name="shiftType" value="◯">
            <label for="tdinnerShift" class="label">ディナー:◯</label>
        </li>

        <li>
            <input type="radio" id="t17Shift" name="shiftType" value="◯17">
            <label for="t17Shift" class="label">17時～</label>
        </li>
        <li>
            <input type="radio" id="torShift" name="shiftType" value="☆">
            <label for="torShift" class="label">どっちでも:☆</label>
        </li>
        <li>
            <input type="radio" id="tfullShift" name="shiftType" value="◎">
            <label for="tfullShift" class="label">オーラス:◎</label>
        </li>
        <li>
            <input type="radio" id="tNoShift" name="shiftType" value="✕">
            <label for="tNoShift" class="label">休み:×</label>
        </li>
    </ul>
    
    <br>

    
    <!-- <button id="deleteShift">削除</button> -->
    <button id="saveShift">保存</button>

</div>


<!-- <div id="shiftInfoContainer"></div> -->

<script>

    function getCookie(name) {
       let cookieValue = null;
       if (document.cookie && document.cookie !== '') {
           const cookies = document.cookie.split(';');
           for (let i = 0; i < cookies.length; i++) {
               const cookie = cookies[i].trim();
               if (cookie.substring(0, name.length + 1) === (name + '=')) {
                   cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                   break;
               }
           }
       }
       return cookieValue;
   }

   const csrfToken = getCookie('csrftoken');
   const shiftData = JSON.parse('{{ shift_data|escapejs }}');
   shifts = shiftData; 
   const currentUserID = "{{ request.user.account_id }}";
//    console.log("user.account_id", currentID);

</script>


<script src="../../static/js/table.js"> </script>


{% endif %}
{% endblock content %}